START TRANSACTION ISOLATION LEVEL SERIALIZABLE; COMMIT AND CHAIN; COMMIT ;
START TRANSACTION ISOLATION LEVEL SERIALIZABLE; COMMIT ;
START TRANSACTION ISOLATION LEVEL REPEATABLE READ; savepoint s; COMMIT AND CHAIN;
SHOW transaction_isolation; -- transaction is active at this point
COMMIT;
START TRANSACTION ISOLATION LEVEL SERIALIZABLE; COMMIT;
START TRANSACTION ISOLATION LEVEL REPEATABLE READ; savepoint s; COMMIT AND CHAIN;
SHOW transaction_isolation; -- transaction is active at this point
COMMIT;
