SELECT 3 = ANY (ARRAY[1, NULL]);
SELECT NULL = ANY (ARRAY[1, NULL]);
SELECT 3 IN (SELECT UNNEST(ARRAY[1, NULL]));
SELECT NULL IN (SELECT UNNEST(ARRAY[1, NULL]));
SELECT ARRAY[1, 2] = ARRAY[1, NULL];
SELECT ARRAY[1, NULL] = ARRAY[1, NULL];
