SELECT '1' IN (SELECT (SELECT '1'::BOOL));
SELECT '1' = ANY (SELECT (SELECT '1'::BOOL));
SELECT '1' = ALL (SELECT (SELECT '1'::BOOL));
SELECT '1' = ALL (SELECT (SELECT '1'::TEXT));
SELECT '1' = ALL (SELECT (SELECT '1'::INT));
SELECT '1' IN (SELECT (SELECT '1'::INT));
SELECT '1' = ANY (SELECT (SELECT '1'::TEXT));
